services:
  mongo:
    image: mongo:4.4
    container_name: container-ya-mongo
    ports:
      - "27017:27017"
    networks:
      - yolo-net
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=yolomy
  backend:
    image: mwas121/yolo-backend:1.0.0
    container_name: container-ya-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://container-ya-mongo:27017/yolomy
    depends_on:
      - mongo
    networks:
      - yolo-net
  frontend:
    image: mwas121/yolo-client:1.0.0
    container_name: container-ya-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - yolo-net
networks:
  yolo-net:
    driver: bridge
volumes:
  mongo-data:
