version: "3.8"
services:
  frontend:
    image: mwas121/yolo-client:1.0.0
    container_name: yolo-client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-net
    stdin_open: true
    tty: true

  backend:
    image: mwas121/yolo-backend:1.0.0
    container_name: yolo-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/yolomy
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-net
    restart: always

  mongodb:
    image: mongo:latest
    container_name: yolo-mongo
    ports:
      - "27017:27017"
    volumes:
      - app-mongo-data:/data/db
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.0.0/16

volumes:
  app-mongo-data:
    driver: local
