services:
  yolo-client:
    container_name: container-ya-frontend
    image: mwas121/yolo-client:1.0.0
    build: ./client
    ports:
      - "3000:80"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - yolo-net
    depends_on:
      - yolo-backend

  yolo-backend:
    container_name: container-ya-backend
    image: mwas121/yolo-backend:1.0.0
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - yolo-net
    depends_on:
      mongo:
        condition: service_healthy
    restart: always

  mongo:
    container_name: container-ya-mongo
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - yolo-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 15s
      timeout: 10s
      retries: 5

networks:
  yolo-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local
