
services:
  yolo-client:
    container_name: container-ya-frontend
    image: mwas121/yolo-client:1.0.0
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - yolo-net
    depends_on:
      - yolo-backend

  yolo-backend:
    container_name: container-ya-backend
    image: mwas121/yolo-backend:1.0.0.0
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - yolo-net
    depends_on:
      - mongo

  mongo:
    container_name: container-ya-mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - yolo-net
    volumes:
      - mongo-data:/data/db

networks:
  yolo-net:
    driver: bridge

volumes:
  mongo-data:
