---
- name: Clone the repository
  git:
    repo: "{{ repo_url | default('https://github.com/nuisance-07/yolo.git') }}"
    dest: "{{ repo_dest | default('/home/vagrant/yolo') }}"
    version: master
    force: yes
  become: true
  become_user: vagrant
  tags:
    - setup-repo
- name: Create Docker network
  docker_network:
    name: "{{ network_name | default('yolo-net') }}"
    state: present
  become: true
  tags:
    - setup-network
- name: Run frontend container
  docker_container:
    name: "{{ frontend_container.name }}"
    image: "{{ frontend_container.image }}"
    state: started
    restart_policy: always
    ports: "{{ frontend_container.port_mapping }}"
    volumes:
      - "{{ frontend_container.volume_mapping }}"
      - "{{ repo_dest | default('/home/vagrant/yolo') }}/client/node_modules:/app/node_modules"
    env: "{{ frontend_container.env_vars }}"
    networks:
      - name: "{{ frontend_container.network }}"
  become: true
  tags:
    - deploy-frontend
