---
- name: Install Git
  apt:
    name: git
    state: present
    update_cache: yes
  become: true
  tags:
    - install-git
- name: Docker installation and configuration
  block:
    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true
      tags:
        - install-docker
    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      become: true
      tags:
        - install-docker
    - name: Install Docker and dependencies
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes
      become: true
      tags:
        - install-docker
    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes
      become: true
      tags:
        - install-docker
    - name: Add vagrant user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes
      become: true
      tags:
        - install-docker
